on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize]

name: Build & Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - name: Install bashly
        run: gem install bashly -v 2.0.0
      - name: Compile flynnt agent installer
        run: bashly generate
      - uses: actions/upload-artifact@v7
        with:
          name: flynnt-script
          path: flynnt

  create-release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v8
        with:
          name: flynnt-script
      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: RELEASE_NOTES.md
      - name: Rename script
        run: mv flynnt flynnt.sh
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          files: flynnt.sh
