name: Test
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

concurrency: test

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODES: test-ubuntu-26 test-ubuntu-24 test-debian-13
      K8S_SERVER: https://solitary-base-6289.cloud.flynnt.io
    steps:
      - uses: actions/checkout@v7
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::386089424926:role/github-to-aws-deployment
          role-session-name: GitHubActions
          aws-region: eu-central-1
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.5"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - name: Install bashly
        run: gem install bashly -v 2.0.0
      - name: Compile flynnt agent installer
        run: bashly generate
      - name: test
        env:
          K8S_TOKEN: ${{ secrets.k8s_token }}
          SOPS_AGE_KEY: ${{ secrets.sops_age_key }}
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl
          
          terraform -chdir=tests/terraform init
          terraform -chdir=tests/terraform apply -auto-approve
          
          # bash loop 5 minutes and check every minute if the node is ready
          echo "Checking if all nodes are ready..."
          for i in {1..5}; do
            sleep 60
            echo "Attempt $i."

            all_nodes_ready=true
            for node in $NODES; do
              node_status=$(kubectl --token="$K8S_TOKEN" --server="$K8S_SERVER" get nodes "$node" -o=jsonpath="{.status.conditions[?(@.type=='Ready')].status}" || true)
              if [ "$node_status" != "True" ]; then
                all_nodes_ready=false
                echo "Node $node is not ready."
                break
              fi
            done

            if [ "$all_nodes_ready" = "true" ]; then
              echo "All nodes are ready."
              exit 0
            fi
          done
          echo "Nodes did not become ready within 5 minutes."
          exit 1
      - name: Cleanup
        env:
          K8S_TOKEN: ${{ secrets.k8s_token }}
          SOPS_AGE_KEY: ${{ secrets.sops_age_key }}
        if: always()
        run: |
          terraform -chdir=tests/terraform destroy -auto-approve
          
          for node in $NODES; do
            kubectl --token="$K8S_TOKEN" --server="$K8S_SERVER" delete node "$node" || true
          done
